name: Bug Report
description: Report a bug or issue with the Mergington High School Activities website
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this issue! Please provide as much detail as possible to help us fix it quickly.
  
  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: What is the bug or issue you're experiencing?
      placeholder: "Example: Students are unable to see the list of activities on the homepage"
    validations:
      required: true
  
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: "Example: The activities list should display all available extracurricular activities"
    validations:
      required: true
  
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to the homepage
        2. Scroll to the activities section
        3. Notice that no activities are displayed
    validations:
      required: true
  
  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: What actually happens right now?
      placeholder: "Example: The page shows an empty list with a loading spinner that never stops"
    validations:
      required: false
  
  - type: dropdown
    id: affected-area
    attributes:
      label: Affected Area
      description: Which part of the website is affected?
      options:
        - Activities List
        - Activity Details
        - Student Sign-up
        - Authentication/Login
        - Navigation/Menu
        - Search/Filters
        - Other
    validations:
      required: true
  
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this issue?
      options:
        - Critical - Site is broken or unusable
        - High - Major feature is broken
        - Medium - Feature works but has issues
        - Low - Minor cosmetic or text issue
    validations:
      required: true
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or information about the problem
      placeholder: "Example: This started happening after we updated the activity database last week"
    validations:
      required: false
